FROM danibascon/phpmyadmin7-ubuntu:1
#FROM ubuntu:16.04

#RUN apt install nano apache2 php7.0 libapache2-mod-php7.0  php7.0-mysql phpmyadmin unzip wget -y

ADD wordpress /wordpress

CMD apachectl -D FOREGROUND

